name: Publish to PyPI

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      id-token: write  # Required for PyPI trusted publishing

    steps:
    - uses: actions/checkout@v3

    - name: Install Pixi
      uses: prefix-dev/setup-pixi@v0.4.1

    - name: Install dependencies
      run: pixi install

    - name: Install build dependencies
      run: pixi add build twine

    - name: Build package
      run: pixi run python -m build

    - name: Publish to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1 