name: Create Release

on:
  push:
    tags:
      - 'v*'  # Trigger on version tags

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Needed for creating releases
    steps:
      - uses: actions/checkout@v4
      
      - name: Install Pixi
        uses: prefix-dev/setup-pixi@v0.4.1
        with:
          manifest-path: pyproject.toml

      - name: Install dependencies
        run: |
          pixi install
          pixi run install

      - name: Build package
        run: pixi run build
        
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/*.whl
            dist/*.tar.gz
          draft: false
          prerelease: false
          generate_release_notes: true