name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
    - uses: actions/checkout@v3

    - name: Install Pixi
      uses: prefix-dev/setup-pixi@v0.4.1


    - name: Install dependencies
      run: |
        pixi install --manifest-path pyproject.toml
        pixi run --manifest-path pyproject.toml install

    - name: Run tests
      run: pixi run --manifest-path pyproject.toml test